PROJETOS/tiago/agenda/agenda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contatos.urls', namespace='contatos')),
    path('', include('calendario.urls', namespace='calendario')),
]

PROJETOS/tiago/agenda/calendario/urls.py
from django.urls import path

from . import views

app_name = "calendario"
urlpatterns = [
    path('calendario', views.calendario, name='calendario'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('cadastro_sucesso', views.cadastro_sucesso, name='cadastro_sucesso'),
]

PROJETOS/tiago/agenda/contatos/urls.py
from django.urls import path

from . import views

app_name = "contatos"
urlpatterns = [
    path('', views.contato, name='raiz'),
    path('editar', views.editar_contato, name='editar'),
    path('contato_adicionar', views.adicionar_contato, name='contato_adicionar'),
    path('contato_apagar', views.apagar_contato, name='contato_apagar'),
    path('editarf', views.editar_contato_final, name='editarf'),
    path('sobre', views.sobre, name='sobre'),
]

PROJETOS/tiago/agenda/calendario/models.py
from django.db import models
from django.db.models import CharField
from django.db.models import DateTimeField

class Anotacoes(models.Model):
    nome = CharField(max_length = 200)
    motivo = CharField(max_length = 200, default='')
    data = DateTimeField()


PROJETOS/tiago/agenda/contatos/models.py
from django.db import models
from datetime import date


class ContatoModel(models.Model):
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=20)
    email = models.EmailField()
    endereco = models.CharField(max_length=100)

PROJETOS/tiago/agenda/contatos/forms.py
from django import forms
from django.forms import ModelForm

from contatos.models import ContatoModel


class AgendaForm(ModelForm):
    class Meta:
        model = ContatoModel
        fields = ('nome', 'telefone', 'email', 'endereco') # Campos que serão verificados a validade
        # exclude = ['created_at']
        labels = {
            'nome': 'Nome',
            'telefone': 'Telefone',
            'email': 'E-mail',
            'endereco': 'Endereço',
        }
        widgets = {
            'nome': forms.TextInput(),
            'telefone': forms.TextInput(),
            'email': forms.EmailInput(),
            'endereco': forms.TextInput(),
        }
        error_messages = {
            'nome': {
                'required': ("Digite o nome."),
            },
            'telefone': {
                'required': ("Digite o telefone."),
                'null': ("Não aceito menos de três digitos")
            }
        }

    def clean_nome(self):
        return self.cleaned_data['nome'].title()
        
    def clean_email(self):
        return self.cleaned_data['email']
    def clean_endereco(self):
        return self.cleaned_data['endereco']

    def clean_telefone(self):
        if len(self.cleaned_data['telefone']) > 3:
            return self.cleaned_data['telefone']

PROJETOS/tiago/agenda/calendario/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from datetime import datetime

from calendario.models import Anotacoes

def calendario(request):
    if request.method == "POST":
        chave = int(request.POST.get('chave', ''))
        Anotacoes.objects.filter(pk=chave).delete()

    anotacoes = Anotacoes.objects.filter(data__month = str(datetime.now().month), data__day = str(datetime.now().day))
    todosfuturos = Anotacoes.objects.filter(data__gt = datetime.today()).order_by('data')
    
    contexto = {'anotacoes':anotacoes, 'todosfuturos':todosfuturos}
    return render(request, 'calendario.html', contexto)
    

def cadastro(request):
    return render(request, 'cadastro.html')

def cadastro_sucesso(request):
    if request.method == "POST":
        nome = request.POST.get('nome', '')
        motivo = request.POST.get('motivo', '')
        
        ano = int(request.POST.get('data', '').split('-')[0])
        mes = int(request.POST.get('data', '').split('-')[1])
        dia = int(request.POST.get('data', '').split('-')[2])
        data = datetime(ano, mes, dia)

        f1 = Anotacoes(nome = nome, motivo = motivo, data = data)
        f1.save()
    return render(request, 'cadastro_sucesso.html')

PROJETOS/tiago/agenda/contatos/views.py
from django.shortcuts import render, get_object_or_404
from contatos.models import ContatoModel
from contatos.forms import AgendaForm


def contato(request):
    if request.method == 'POST':
        form = AgendaForm(request.POST)
        if not form.is_valid():
            if 'search' in request.POST:
                terms = request.POST.get('search', '')
                contexto = {
                    'contatos': ContatoModel.objects.all().filter(nome__contains=terms).order_by('nome'),
                    'form': form,
                }
                return render(request, 'contato.html', contexto)
            else:
                contexto = {
                    'contatos': ContatoModel.objects.all().order_by('nome'),
                    'form': form,
                }
                return render(request, 'contato.html', contexto)
        else:
            ContatoModel.objects.create(**form.cleaned_data)
            contexto = {
                'contatos': ContatoModel.objects.all().order_by('nome'),
                'form': AgendaForm(),
            }
            return render(request, 'contato.html', contexto)
    else:
        contexto = {
            'contatos': ContatoModel.objects.all().order_by('nome'),
            'form': AgendaForm(),
        }
        return render(request, 'contato.html', contexto)

def adicionar_contato(request):
    if request.method == 'POST':
        form = AgendaForm(request.POST)
        if not form.is_valid():
            contexto = {
                'contatos': ContatoModel.objects.all().order_by('nome'),
                'form': form,
            }
            return render(request, 'contato.html', contexto)
        else:
            ContatoModel.objects.create(**form.cleaned_data)
            contexto = {
                'contatos': ContatoModel.objects.all().order_by('nome'),
                'form': AgendaForm(),
            }
            return render(request, 'contato.html', contexto)
    else:
        contexto = {
            'form': AgendaForm(),
        }
        return render(request, 'contato_adicionar.html', contexto)

def editar_contato(request):
    if request.method == 'POST':
        chave = int(request.POST.get('chave', ''))
        obj = get_object_or_404(ContatoModel, pk=chave)
        form = AgendaForm(instance=obj)
        context = {'form': form, 'chave': chave}
        return render(request, "editar.html", context)        
    else:
        return render(request, "contato.html")

def editar_contato_final(request):    
    if request.method == 'POST':
        chave = int(request.POST.get('chave', ''))
        form = AgendaForm(request.POST)
        if not form.is_valid():
            obj = get_object_or_404(ContatoModel, pk=chave)
            form = AgendaForm(instance=obj)
            context = {'form': form, 'chave': chave}
            return render(request, "editar.html", context)
        else:
            chave = int(request.POST.get('chave', ''))
            ContatoModel.objects.filter(pk=chave).update(**form.cleaned_data)
            obj = get_object_or_404(ContatoModel, pk=chave)
            form = AgendaForm(instance=obj)
            context = {'form': form, 'chave': chave}
            return render(request, "editarf.html", context)
    return render(request, "editarf.html", context)

def apagar_contato(request):
    if request.method == 'POST':
        chave = int(request.POST.get('chave', ''))
        ContatoModel.objects.filter(pk=chave).delete()
    return render(request, "contato_apagar.html")
    
def sobre(request):
    return render(request, "sobre.html")

PROJETOS/tiago/agenda/calendario/templates/cadastro.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>AgendaPessoal</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!--===============================================================================================-->
		<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<!--===============================================================================================-->
	</head>
	<body>
		<div id="navegacao">
			<div id="area">
					<a href="{% url 'contatos:raiz' %}" style="background-color: transparent; padding: 0">
						<h1 id="logo"><span class="azul">Agenda</span><span class="roxo">Pessoal</span></h1>
					</a>
					<div id="menu">
							<a href="{% url 'contatos:raiz' %}">Contatos</a>
							<a href="{% url 'calendario:calendario' %}">Compromissos</a>
							<a href="{% url 'contatos:sobre' %}">Sobre</a>
					</div>
			</div>
		</div>

	
		<div class="container-contact100">			
			<table border="0" width="100%" id="tabela" >	
				<tr><td > </br></br> </td></tr>
				<tr>
					<td >
						<div class="header-contatos">
							<h1 id="title">Adicionar Compromisso</h1>
						</div>
					</td>
				</tr>
			</table>
			<center>
			<table>
				<col width="300">
				<col width="64">
				<tr><td></br></td></tr>
				<tr>
					<th>
						<div class="wrap-contact100">
							<form action="cadastro_sucesso" method="POST">
								{% csrf_token %}
								{{ form }}

								<label for="nome">Nome:&nbsp;</label>
								<input type="text" id="nome" name="nome" required>
								<br><br>
								
								<label for="motivo">Motivo:&nbsp;</label>
								<input type="text" id="motivo" name="motivo">
								<br><br>
								
								<label for="data">Data</label>
								<input type="date" id="data" name="data" required>
								<br><br>
								
								<center><input type="image" src="{% static 'images/confirm.png' %}" width="64px" height="64px" alt='Submit Form' name="Enviar"></center>
							</form>
						</div>
					</th>
				</tr>
				<tr><td></br></td></tr>
			</table></center>
		</div>

		<div class="footer">
			<p>Desenvolvido por <a href="http://www.tiagoremedio.com.br" target="_blank">Tiago Remédio</a> @ 2018 - Curso de Django por Orlando Saraiva Jr. - Fatec Araras</p>
		</div>

		<!--===============================================================================================-->
		<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
		<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
		<script>
			$(".selection-2").select2({
				minimumResultsForSearch: 20,
				dropdownParent: $('#dropDownSelect1')
			});
		</script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
		<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'js/main.js' %}"></script>
	</body>
</html>

PROJETOS/tiago/agenda/calendario/templates/calendario.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>AgendaPessoal</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!--===============================================================================================-->
		<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<!--===============================================================================================-->
	</head>
	<body>
		<div id="navegacao">
			<div id="area">
				<a href="{% url 'contatos:raiz' %}" style="background-color: transparent; padding: 0">
					<h1 id="logo"><span class="azul">Agenda</span><span class="roxo">Pessoal</span></h1>
				</a>
				<div id="menu">
						<a href="{% url 'contatos:raiz' %}">Contatos</a>
						<a href="{% url 'calendario:calendario' %}">Compromissos</a>
						<a href="{% url 'contatos:sobre' %}">Sobre</a>
				</div>
			</div>
		</div>
	
		<div class="container-contact100">			
			<table border="0" width="100%" id="tabela" >	
				<tr><td > </br></br> </td></tr>
				<tr>
					<td >
						<div class="header-contatos">
							<a href="{% url 'calendario:cadastro' %}" style="background-color: transparent; padding: 0">
								<img src="{% static 'images/add.png' %}" height="64" width="64">
							</a>
							<h1 id="title">Compromissos</h1>
						</div>
					</td>
				</tr>
			</table>
			<center>
			<table>
				<col width="300">
				<col width="64">
				<tr><td></br></td></tr>
				<tr>
					<th>
						<div class="wrap-contact100">
							{% if anotacoes|length > 0 %}
								<h3>Compromissos de Hoje</h3>
								{% for anotacao in anotacoes %}
									<hr>
									<span class="label-input100"><b>Compromisso:&nbsp;&nbsp;</b></span>{{ anotacao.nome }}
									<br>
									{% if anotacao.motivo != '' %}
										<span class="label-input100"><b>Descrição:&nbsp;&nbsp;</b></span>{{ anotacao.motivo }}
									{% endif %}
									<form action="calendario" method="POST">
										{% csrf_token %}
										<input type='hidden' name='chave' value='{{ anotacao.pk }}'/>
										<input type="image" src="{% static 'images/delete.png' %}" width="32px" height="32px" alt='Submit Form' name="Salvar informações">
									</form>
								{% endfor %}
							{% else %}
								<h3>Hoje não há compromissos.</h3>
							{% endif %}
						</div>
					</th>
				</tr>
				<tr><td></br></td></tr>				
				<tr>
					<th>
						<div class="wrap-contact100">
						{% if todosfuturos|length > 0 %}
							<h3>Compromissos Futuros</h3>
							{% for todofuturo in todosfuturos %}
								<hr>
								<span class="label-input100"><b>Compromisso:&nbsp;&nbsp;</b></span>{{ todofuturo.nome }}
								<br>
								{% if todofuturo.motivo != '' %}
									<span class="label-input100"><b>Descrição:&nbsp;&nbsp;</b></span>{{ todofuturo.motivo }}
									<br>
								{% endif %}
								<span class="label-input100"><b>Data:&nbsp;&nbsp;</b></span>{{ todofuturo.data|date:'Y-m-d' }}
								<form action="calendario" method="POST">
									{% csrf_token %}
									<input type='hidden' name='chave' value='{{ todofuturo.pk }}'/>
									<input type="image" src="{% static 'images/delete.png' %}" width="32px" height="32px" alt='Submit Form' name="Salvar informações">
								</form>
							{% endfor %}
						{% else %}
							<h3>Não há compromissos futuros.</h3>
						{% endif %}
						</div>
					</th>
				</tr>
				<tr><td></br></td></tr>	
			</table></center>
		</div>

		<div class="footer">
			<p>Desenvolvido por <a href="http://www.tiagoremedio.com.br" target="_blank">Tiago Remédio</a> @ 2018 - Curso de Django por Orlando Saraiva Jr. - Fatec Araras</p>
		</div>

		<!--===============================================================================================-->
		<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
		<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
		<script>
			$(".selection-2").select2({
				minimumResultsForSearch: 20,
				dropdownParent: $('#dropDownSelect1')
			});
		</script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
		<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'js/main.js' %}"></script>
	</body>
</html>

PROJETOS/tiago/agenda/contatos/templates/contato.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>AgendaPessoal</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!--===============================================================================================-->
		<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<!--===============================================================================================-->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
	<body>
		<div id="navegacao">
			<div id="area">
					<a href="{% url 'contatos:raiz' %}" style="background-color: transparent; padding: 0">
						<h1 id="logo"><span class="azul">Agenda</span><span class="roxo">Pessoal</span></h1>
					</a>
					<div id="menu">
							<a href="{% url 'contatos:raiz' %}">Contatos</a>
							<a href="{% url 'calendario:calendario' %}">Compromissos</a>
							<a href="{% url 'contatos:sobre' %}">Sobre</a>
					</div>
			</div>
		</div>

	
		<div class="container-contact100">		
		</br></br>
			<center>
				<form class="example" action="." method="POST">
					{% csrf_token %}
					<input type="text" placeholder="Procurar..." name="search">
					<button type="submit"><i class="fa fa-search"></i></button>
				</form>
			</center>

			<table border="0" width="100%" id="tabela" >	
				<tr><td > </br></br> </td></tr>
				<tr>
					<td >
						<div class="header-contatos">
							<a href="{% url 'contatos:contato_adicionar' %}" style="background-color: transparent; padding: 0">
								<img src="{% static 'images/add.png' %}" height="64" width="64">
							</a>
							<h1 id="title">Contatos</h1>
						</div>
					</td>
				</tr>
			</table>
			<center>
			<table>
				<col width="300">
				<col width="64">
				<tr><td></br></td></tr>
				{% if contatos %}
					{% for contato in contatos %}
					
						<tr>
							<th>
								<div class="wrap-contact100">				
									<span>
										<h2>{{ contato.nome }}</h2></br>
									</span>

									<span class="label-input100"><b>Telefone:&nbsp;&nbsp;</b></span>	{{ contato.telefone }} </br>
									<span class="label-input100"><b>E-mail:&nbsp;&nbsp;</b></span> {{ contato.email }} </br>
									<span class="label-input100"><b>Endereço:&nbsp;&nbsp;</b></span> {{ contato.endereco }} </br>
								</div>
							</th>
							<th>
								<div>
									<form action="editar" method="POST">
										{% csrf_token %}
										<input type='hidden' name='chave' value='{{ contato.pk }}'/>
										<input type="image" src="{% static 'images/edit.png' %}" width="64px" height="64px" alt='Submit Form' name="Salvar informações">
									</form>
								</div>
								<div>
									<form action="contato_apagar" method="POST">
										{% csrf_token %}
										<input type='hidden' name='chave' value='{{ contato.pk }}'/>
										<input type="image" src="{% static 'images/delete.png' %}" width="64px" height="64px" alt='Submit Form' name="Salvar informações">
									</form>
								</div>
							</th>
						</tr>
						<tr><td></br></td></tr>					
					{% endfor %}
				{% else %}
				<tr>
					<th>
						<div class="wrap-contact100">				
							<h2>Não há contatos cadastrados.</h2>
						</div>
					</th>
				</tr>
				<tr><td></br></td></tr>	
				<tr><td></br></td></tr>			
				{% endif %}
			</table>	
			</center>
		</div>

		<div class="footer">
			<p>Desenvolvido por <a href="http://www.tiagoremedio.com.br" target="_blank">Tiago Remédio</a> @ 2018 - Curso de Django por Orlando Saraiva Jr. - Fatec Araras</p>
		</div>

		<!--===============================================================================================-->
		<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
		<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
		<script>
			$(".selection-2").select2({
				minimumResultsForSearch: 20,
				dropdownParent: $('#dropDownSelect1')
			});
		</script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
		<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'js/main.js' %}"></script>
	</body>
</html>